---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

script:
  - yarn build
  - yarn test
